### ISSUE TITLE
Support for GDScript

### ISSUE THREAD

**Issue by italodirenzo93** [JetBrains/godot-support#88] opened 2022-12-14 15:05 UTC
While this plugin is understandably focused on C# primarily, it would be very handy to also support GDScript syntax highlighting (and eventually intellisense/debugging support). The rationale for this is that some Godot projects contain a mix of C# and GDScript code. Having the ability to use Rider for editing/debugging in both languages saves on iteration time by not having to repeatedly switch between environments when editing/debugging the two languages.

**Comment by PandoCyclone** [comment] 2022-12-19 14:38
Bruh, does that even related

**Comment by cpuccino** [comment] 2023-05-19 07:26
+1 - This would be an awesome add.

**Comment by Perndoe** [comment] 2023-05-19 14:14
There is already a plugin out there tho

**Comment by cpuccino** [comment] 2023-05-25 09:38
Doesn't really work very well or at all, on godot 4 at the very least.

**Comment by italodirenzo93** [comment] 2023-05-25 15:02
It's been a while since I created this issue but my main motivation was that it would be a great workflow improvement to be able to edit & debug both GDScript and C# code from Rider. That way you can follow execution flow across languages in a single debugging environment without having to bounce between the Godot editor and Rider.

**Comment by jsbeckr** [comment] 2023-07-04 12:15
I would like to see that feature as well. There is another plugin [here](https://gitlab.com/IceExplosive/gdscript) that aims to support gdscript in IntelliJ. Maybe they are willing to implement LSP Support for Godot.

**Comment by godotg** [comment] 2023-09-22 10:53
godot is future，so GdScript is future，not C#

**Comment by Perndoe** [comment] 2023-09-23 05:31
> godot is future，so GdScript is future，not C#

What the h do you mean by saying this? C# provides a better performance and since the Unity game engine is being hated ppl tend to switch to Godot cuz it has Csharp and not any other game engines

**Comment by godotg** [comment] 2023-09-26 11:11
> > godot is future，so GdScript is future，not C#
> 
> What the h do you mean by saying this? C# provides a better performance and since the Unity game engine is being hated ppl tend to switch to Godot cuz it has Csharp and not any other game engines

C# takes too long to compile and is not lightweight enough

**Comment by Perndoe** [comment] 2023-09-26 11:44
> > > godot is future，so GdScript is future，not C#
> > 
> > 
> > What the h do you mean by saying this? C# provides a better performance and since the Unity game engine is being hated ppl tend to switch to Godot cuz it has Csharp and not any other game engines
> 
> C# takes too long to compile and is not lightweight enough

I think you are calling yourself an impatient person and the performance is way better in C#. To not ruin this suggestion I will stop talking ABT C#

**Comment by godotg** [comment] 2023-09-27 04:38
C# can not run in android editor，If I  really need performance ，cpp is my choice

**Comment by WarrenMarshall** [comment] 2023-11-27 09:24
gdscript support would be amazing!  I would love to move away from VS Code and work entirely within the JetBrains eco system.

**Comment by van800** [comment] 2023-11-27 10:37
Last week I have published an update to the Rider Godot plugin applicable for Rider 2023.3 EAP builds.
Now all major Godot file types got basic highlighting.
![image](https://github.com/JetBrains/godot-support/assets/1482681/401e4f86-f5e7-407f-aa5c-c41b240ebb8b)
And I am doing experiments with LSP targeting next iteration Rider 2024.x.

**Comment by WarrenMarshall** [comment] 2023-11-27 13:46
The hero we need!

**Comment by godotg** [comment] 2023-11-28 02:16
amazing！

**Comment by WarrenMarshall** [comment] 2023-11-29 09:03
@van800 - Set up a Patreon or something. You have my axe.  And my sword.

**Comment by van800** [comment] 2023-12-04 17:06
If I may ask for your input on a default behavior question.
The alternatives seems the following:
 - automatically start a headless GodotEditor
 - automatically start GodotEditor
 - try to connect the running GodotEditor or wait for it to be started manually

**Comment by van800** [comment] 2023-12-06 07:56
related Godot proposal https://github.com/godotengine/godot-proposals/issues/8593

**Comment by SommerEngineering** [comment] 2023-12-31 22:43
> If I may ask for your input on a default behavior question. The alternatives seems the following:
> 
>     * automatically start a headless GodotEditor
>     * automatically start GodotEditor
>     * try to connect the running GodotEditor or wait for it to be started manually

In my opinion, the plugin should wait for the editor (your third point). This way we save resources (RAM, CPU) because only one Godot process is running.

**Comment by van800** [comment] 2024-01-25 07:45
The integration of Language Server Protocol (LSP) for GDScript is available in the public 2024.1 EAP1 build of Rider with a recent Godot support plugin. It is disabled by default setting in Rider (Godot Engine - Connecting LSP server).
If you encounter any problems, please report them in Rider with Help -> Report a Bug. If the problem is directly related to this plugin, you may use `Issues` here on github.

This issue remains open.
 
<img width="868" alt="image" src="https://github.com/JetBrains/godot-support/assets/1482681/e2e7142a-79a2-458d-9edd-a7e7c8555c11">

**Comment by WarrenMarshall** [comment] 2024-01-25 10:09
Really waiting for GDScript support but this is a great first step!  Great to see it ...

**Comment by Sygan** [comment] 2024-01-27 00:03
I've recently started experimenting with Godot and the thing that I miss the most even after writing just a few scripts are the refactoring capabilities of Rider that I really rely upon in my work. I can't wait to see full GD Script support with refactoring capabilities. Keep up the good work and thank you so much for it.

**Comment by WarrenMarshall** [comment] 2024-01-27 09:27
100%, being able to refactor GDScript on a project-wide basis would be game changing.

**Comment by MRxRadex** [comment] 2024-02-10 10:59
For whatever reason at EAP 4 I do not see Godot settings at all on macOS Sonoma. And no support of .gd files as a result
<img width="741" alt="image" src="https://github.com/JetBrains/godot-support/assets/5471816/1b3d034e-ec7f-4313-9b38-c119e67c6e7d">

**Comment by AlighaThor** [comment] 2024-02-18 13:20
@WarrenMarshall You can use in the meantime GDFormat (a python lib) and then create a custom command in Jetbrains that runs it (for current file or whole repo as desired), and the assign your custom keymap to run that custom command. Works super good as a temp alternative.

**Comment by IkutiDev** [comment] 2024-05-05 13:44
Enjoying what there is so far. Currently just waiting for the refactoring methods and the find usages working, after which I will be perfectly happy with this implementation ❤️

**Comment by tkgalk** [comment] 2024-05-06 22:06
> The integration of Language Server Protocol (LSP) for GDScript is available in the public 2024.1 EAP1 build of Rider with a recent Godot support plugin.

Cheers. Renewing Rider just for this, hoping for more features and tighter integration in the future. :)

**Comment by godotg** [comment] 2024-05-16 09:24
I have been using it for a while and it is very good. I look forward to continuing to update.

**Comment by IkutiDev** [comment] 2024-05-30 10:36
Debugging inside Rider sounds superb! ❤️  Hopefully it will be merged soon.

I personally also have 1 question regarding gdscript implementation. Is there a plan to add "see usages" feature? It's what I'm really missing coming from the C# and sadly it's not available inside the base script editor of Godot. (but I have seen it working inside other plugin for rider for gdscript).

Also important info for now anyone wanting to use rider for gdscript, don't override the inside editor with the external editor inside editor settings, if you plan to write custom resources, plugins or tool scripts. Since currently they don't update correctly from outside text/code editors, they only update when opening the internal godot code editor.

**Comment by van800** [comment] 2024-05-30 19:54
Find Usages feature is available in the third party **GdScript** plugin from IceExplosive and for the upcoming Rider 2024.2, I have ensured the compatibility with that plugin.

However Find Usages via LSP is also in the works https://youtrack.jetbrains.com/issue/IJPL-848/LSP-API-support-Find-Usages-textDocument-references-request

**Comment by ArSn** [comment] 2024-06-01 18:32
Thank you for your continued work on this, this is already a bless! 🙇🏻‍♂️ 

If at all possible, could we get some coloring for functions (when they are called) and variables? So far a lot of it is just white despite the highlighting generally working, example:

![image](https://github.com/JetBrains/godot-support/assets/2803693/795681ee-08a9-4e73-9546-8ba6991c2eb6)

Also note the `==` here looks a bit wonky, not sure why that is either, but not that important to me personally.

Thanks again!

**Comment by van800** [comment] 2024-06-02 10:40
@ArSn 
Hi!
There seem to be an issue, which I can't reproduce easily on my end (with Rider 2024.1.2).
Would you please report via Help->Report a Bug, agree to attach logs?
<img width="867" alt="image" src="https://github.com/JetBrains/godot-support/assets/1482681/147bd0b7-2516-47c9-872a-2832a7cc1d17">

**Comment by ArSn** [comment] 2024-06-02 14:00
@van800 Interesting, I somehow thought it was just not covered, or I would have reported a bug in the first place as you asked. Anyhow, reported it now: https://youtrack.jetbrains.com/issue/RIDER-112960/GdScript-syntax-highlighting-not-working-as-expected

**Comment by godotg** [comment] 2024-07-17 02:47
> **GdScript** plugin from IceExplosive

I can't find GdScript plugin from IceExplosive. My redier version is 2024.1.4.

**Comment by van800** [comment] 2024-07-17 09:28
> > **GdScript** plugin from IceExplosive
> 
> I can't find GdScript plugin from IceExplosive. My redier version is 2024.1.4.

My bad. It can also be refered as GdScript from David Horáček

**Comment by godotg** [comment] 2024-08-17 08:55
![image](https://github.com/user-attachments/assets/0e0a026c-f70b-4a00-ac31-e8189fa44770)

JetBrains Rider 2024.2  Build #RD-242.20224.401, built on August 14, 2024

some error occurs when I debug scene. 

![image](https://github.com/user-attachments/assets/41001af3-df07-4455-9f63-9a7c5accd679)

![image](https://github.com/user-attachments/assets/b0abfc4e-51de-421c-a5b8-60cfb83216a4)

**Comment by van800** [comment] 2024-08-18 08:20
@jaysunxiao fordebugging gdscript, please use the "GDScript Start and Debug" configuration.
If your project doesn't have any C#, you would not need to solve any MSBuild issues.

**Comment by van800** [comment] 2024-08-18 08:23
Our official docs are public https://www.jetbrains.com/help/rider/2024.2/Godot.html
If there is anything missing please comment here or create an issue with Help->Report a Bug.
Thanks!

**Comment by jaysunxiao** [comment] 2024-08-18 12:26
> @jaysunxiao for debugging gdscript, please use the "GDScript Start and Debug" configuration. If your project doesn't have any C#, you would not need to solve any MSBuild issues.
> 
> I have created an issue https://youtrack.jetbrains.com/issue/RIDER-115995/Run-Debug-a-specific-scene-functionality-doesnt-support-GDScript

This solved my problem.   Thanks a lot.

**Comment by van800** [comment] 2024-08-26 06:25
I am closing the issue now since the Rider version with GDScript support has been released. 
However, please continue sharing any inconveniences you encounter.

**Closed by van800** 2024-08-26 06:25 UTC
